# cspell: disable
version: "3"

tasks:
  default:
    - task: fix
    - task: format

  lint:
    cmds:
      - ruff check --respect-gitignore src
      # - mypy --install-types --non-interactive src
      # - pyright src

  format:
    ignore_error: true
    cmd: ruff format --respect-gitignore src

  fix:
    cmd: ruff check --respect-gitignore --fix src

  dev-install:
    cmds:
      - pip install --upgrade ruff pyright pre-commit mypy changelog-parser semver tomlkit

  dev-setup:
    deps:
      - task: dev-install
    cmds:
      - pre-commit install

  clean:
    cmds:
      - find . -type d -name "__pycache__" -exec rm -rf {} +
      - rm -rf site release_body.md .*_cache *.log dist

  release:
    cmd: python3 tools/release.py {{.CLI_ARGS}}

  docs-setup:
    cmds:
      - pip install mkdocs mkdocs-material mkdocs-git-revision-date-localized-plugin 'mkdocstrings[python]'
